In [5]:
import pandas as pd

df = pd.read_csv("../data/raw/credit_card_customer_churn_dataset.csv")

print(df.shape)
df.head()

(100000, 40)

,customer_id,age,gender,marital_status,education_level,employment_status,income,city,credit_score,account_age_months,...,support_satisfaction,reward_points,offers_received,offers_redeemed,financial_stress_score,engagement_score,customer_value_score,churn_risk_score,churn_probability,churned
0,CUST-0000001,50,Male,Divorced,Bachelor,Employed,31679.55,San Diego,685,151,...,4.1,728,3,1,50.33,74.89,54.35,13.00,0.1300,0
1,CUST-0000002,42,Female,Married,Bachelor,Self-Employed,83618.66,Los Angeles,732,81,...,3.3,13537,3,2,17.70,85.36,99.34,4.30,0.0430,0
2,CUST-0000003,52,Male,Married,Bachelor,Self-Employed,134295.30,Phoenix,777,41,...,3.2,4671,4,2,15.67,74.81,30.56,3.32,0.0332,0
3,CUST-0000004,63,Female,Married,Bachelor,Employed,100983.46,New York,708,54,...,3.1,12694,4,0,13.13,47.55,80.07,19.30,0.1930,0
4,CUST-0000005,40,Male,Married,Bachelor,Employed,89736.89,Other,664,95,...,4.5,37007,1,1,44.25,58.71,100.00,15.10,0.1510,0

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 40 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   customer_id                 100000 non-null  str
 1   age                         100000 non-null  int64
 2   gender                      100000 non-null  str
 3   marital_status              100000 non-null  str
 4   education_level             100000 non-null  str
 5   employment_status           100000 non-null  str
 6   income                      100000 non-null  float64
 7   city                        100000 non-null  str
 8   credit_score                100000 non-null  int64
 9   account_age_months          100000 non-null  int64
 10  card_type                   100000 non-null  str
 11  credit_limit                100000 non-null  float64
 12  annual_fee                  100000 non-null  int64
 13  interest_rate               100000 non-null  float64
 14  num_products                100000 non-null  int64
 15  has_loan                    100000 non-null  int64
 16  has_savings_account         100000 non-null  int64
 17  monthly_spending            100000 non-null  float64
 18  avg_transaction_amount      100000 non-null  float64
 19  monthly_transactions        100000 non-null  int64
 20  online_transactions         100000 non-null  int64
 21  international_transactions  100000 non-null  int64
 22  cash_withdrawals            100000 non-null  int64
 23  utilization_ratio           100000 non-null  float64
 24  payment_delay_count         100000 non-null  int64
 25  late_payment_amount         100000 non-null  float64
 26  app_logins_monthly          100000 non-null  int64
 27  website_visits_monthly      100000 non-null  int64
 28  customer_service_calls      100000 non-null  int64
 29  complaints_count            100000 non-null  int64
 30  support_satisfaction        100000 non-null  float64
 31  reward_points               100000 non-null  int64
 32  offers_received             100000 non-null  int64
 33  offers_redeemed             100000 non-null  int64
 34  financial_stress_score      100000 non-null  float64
 35  engagement_score            100000 non-null  float64
 36  customer_value_score        100000 non-null  float64
 37  churn_risk_score            100000 non-null  float64
 38  churn_probability           100000 non-null  float64
 39  churned                     100000 non-null  int64
dtypes: float64(13), int64(20), str(7)
memory usage: 30.5 MB

In [8]:
df.columns.tolist()

['customer_id',
 'age',
 'gender',
 'marital_status',
 'education_level',
 'employment_status',
 'income',
 'city',
 'credit_score',
 'account_age_months',
 'card_type',
 'credit_limit',
 'annual_fee',
 'interest_rate',
 'num_products',
 'has_loan',
 'has_savings_account',
 'monthly_spending',
 'avg_transaction_amount',
 'monthly_transactions',
 'online_transactions',
 'international_transactions',
 'cash_withdrawals',
 'utilization_ratio',
 'payment_delay_count',
 'late_payment_amount',
 'app_logins_monthly',
 'website_visits_monthly',
 'customer_service_calls',
 'complaints_count',
 'support_satisfaction',
 'reward_points',
 'offers_received',
 'offers_redeemed',
 'financial_stress_score',
 'engagement_score',
 'customer_value_score',
 'churn_risk_score',
 'churn_probability',
 'churned']

In [9]:
print("Missing values:")
print(df.isnull().sum().sort_values(ascending=False))

print("\nDuplicate rows:")
print(df.duplicated().sum())

Missing values:
customer_id                   0
age                           0
gender                        0
marital_status                0
education_level               0
employment_status             0
income                        0
city                          0
credit_score                  0
account_age_months            0
card_type                     0
credit_limit                  0
annual_fee                    0
interest_rate                 0
num_products                  0
has_loan                      0
has_savings_account           0
monthly_spending              0
avg_transaction_amount        0
monthly_transactions          0
online_transactions           0
international_transactions    0
cash_withdrawals              0
utilization_ratio             0
payment_delay_count           0
late_payment_amount           0
app_logins_monthly            0
website_visits_monthly        0
customer_service_calls        0
complaints_count              0
support_satisfaction          0
reward_points                 0
offers_received               0
offers_redeemed               0
financial_stress_score        0
engagement_score              0
customer_value_score          0
churn_risk_score              0
churn_probability             0
churned                       0
dtype: int64

Duplicate rows:
0

In [12]:
df["churned"].value_counts()

churned
0    80542
1    19458
Name: count, dtype: int64

In [13]:
df["churned"].value_counts(normalize=True) * 100

churned
0    80.542
1    19.458
Name: proportion, dtype: float64

In [14]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,100000.0,43.634520,12.720601,18.0000,35.0000,44.0000,52.0000,85.0000
income,100000.0,80669.829262,52343.665518,15000.0000,44670.9525,67196.3300,101188.7175,350000.0000
credit_score,100000.0,689.076850,78.320767,344.0000,636.0000,690.0000,744.0000,850.0000
account_age_months,100000.0,42.436910,41.955380,1.0000,12.0000,30.0000,58.0000,490.0000
credit_limit,100000.0,17877.790000,14826.138205,1000.0000,7700.0000,13400.0000,23100.0000,75000.0000
annual_fee,100000.0,74.029000,117.268259,0.0000,0.0000,50.0000,150.0000,450.0000
interest_rate,100000.0,16.676273,2.725795,8.9900,14.7900,16.6600,18.5300,28.5200
num_products,100000.0,1.798710,0.870379,1.0000,1.0000,2.0000,2.0000,4.0000
has_loan,100000.0,0.350500,0.477129,0.0000,0.0000,0.0000,1.0000,1.0000
has_savings_account,100000.0,0.598420,0.490220,0.0000,0.0000,1.0000,1.0000,1.0000
monthly_spending,100000.0,6098.301395,6311.842032,50.0000,2073.8050,4108.5050,7773.4550,60000.0000
avg_transaction_amount,100000.0,82.563695,36.204345,25.0300,56.3075,80.6150,104.3100,400.0000
monthly_transactions,100000.0,73.055180,50.678979,1.0000,29.0000,60.0000,123.0000,150.0000
online_transactions,100000.0,36.005850,29.609507,0.0000,12.0000,28.0000,53.0000,119.0000
international_transactions,100000.0,6.267300,10.959182,0.0000,0.0000,2.0000,7.0000,119.0000
cash_withdrawals,100000.0,1.204380,1.100482,0.0000,0.0000,1.0000,2.0000,10.0000
utilization_ratio,100000.0,0.378698,0.172453,0.0100,0.2500,0.3610,0.4910,0.9900
payment_delay_count,100000.0,0.428790,0.781675,0.0000,0.0000,0.0000,1.0000,9.0000
late_payment_amount,100000.0,19.710776,50.401669,0.0000,0.0000,0.0000,15.0000,500.0000
app_logins_monthly,100000.0,12.000270,3.471013,1.0000,10.0000,12.0000,14.0000,28.0000
website_visits_monthly,100000.0,5.996880,2.438030,0.0000,4.0000,6.0000,8.0000,19.0000
customer_service_calls,100000.0,1.502990,1.933553,0.0000,0.0000,1.0000,2.0000,20.0000
complaints_count,100000.0,0.604860,0.984548,0.0000,0.0000,0.0000,1.0000,13.0000
support_satisfaction,100000.0,3.454744,0.890964,1.0000,2.9000,3.6000,4.1000,5.0000
reward_points,100000.0,7017.855930,7494.044255,40.0000,2323.0000,4635.5000,8905.0000,87409.0000
offers_received,100000.0,3.001990,1.729241,0.0000,2.0000,3.0000,4.0000,13.0000
offers_redeemed,100000.0,1.050780,1.024740,0.0000,0.0000,1.0000,2.0000,8.0000
financial_stress_score,100000.0,28.221484,15.265985,0.0000,17.6500,26.0400,36.2000,100.0000
engagement_score,100000.0,65.245465,15.570877,10.0100,54.0900,64.5500,75.7500,100.0000
customer_value_score,100000.0,50.019722,23.455054,0.7700,30.9600,46.0400,65.7800,100.0000
churn_risk_score,100000.0,19.459803,21.883271,0.0600,4.2800,10.5800,26.1200,99.9400
churn_probability,100000.0,0.194598,0.218833,0.0006,0.0428,0.1058,0.2612,0.9994
churned,100000.0,0.194580,0.395879,0.0000,0.0000,0.0000,0.0000,1.0000

In [15]:
categorical_cols = df.select_dtypes(include="object").columns

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).head(10))

--- customer_id ---
customer_id
CUST-0000001    1
CUST-0000002    1
CUST-0000003    1
CUST-0000004    1
CUST-0000005    1
CUST-0000006    1
CUST-0000007    1
CUST-0000008    1
CUST-0000009    1
CUST-0000010    1
Name: count, dtype: int64

--- gender ---
gender
Female    49193
Male      48794
Other      2013
Name: count, dtype: int64

--- marital_status ---
marital_status
Married     48091
Single      34995
Divorced    11865
Widowed      5049
Name: count, dtype: int64

--- education_level ---
education_level
Bachelor       39937
High School    24953
Associate      15110
Master         15032
Doctorate       4968
Name: count, dtype: int64

--- employment_status ---
employment_status
Employed         62082
Self-Employed    15039
Retired           9947
Unemployed        7930
Student           5002
Name: count, dtype: int64

--- city ---
city
Other           42047
New York        11832
Los Angeles     10021
Chicago          8126
Houston          6015
Phoenix          5027
Philadelphia     4965
San Antonio      4008
San Diego        3984
Dallas           3975
Name: count, dtype: int64

--- card_type ---
card_type
Standard    45048
Silver      29768
Gold        18061
Platinum     7123
Name: count, dtype: int64

C:\Users\ASUS\AppData\Local\Temp\ipykernel_8404\2775710678.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns

In [16]:
quality_checks = {
    "duplicate_customer_id": df["customer_id"].duplicated().sum(),
    "missing_customer_id": df["customer_id"].isna().sum(),
    "invalid_churned": (~df["churned"].isin([0, 1])).sum(),
    "invalid_credit_score": ((df["credit_score"] < 300) | (df["credit_score"] > 850)).sum(),
    "invalid_utilization": ((df["utilization_ratio"] < 0) | (df["utilization_ratio"] > 1)).sum()
}

quality_checks

{'duplicate_customer_id': np.int64(0),
 'missing_customer_id': np.int64(0),
 'invalid_churned': np.int64(0),
 'invalid_credit_score': np.int64(0),
 'invalid_utilization': np.int64(0)}

In [17]:
numeric_cols = df.select_dtypes(include="number").columns

negative_counts = {}

for col in numeric_cols:
    count = (df[col] < 0).sum()
    if count > 0:
        negative_counts[col] = count

negative_counts

{}

In [18]:
audit_summary = {
    "rows": df.shape[0],
    "columns": df.shape[1],
    "missing_values": int(df.isnull().sum().sum()),
    "duplicate_rows": int(df.duplicated().sum()),
    "duplicate_customer_ids": int(df["customer_id"].duplicated().sum()),
    "churn_rate": round(df["churned"].mean() * 100, 2),
    "invalid_credit_scores": int(
        ((df["credit_score"] < 300) | (df["credit_score"] > 850)).sum()
    ),
    "invalid_utilization": int(
        ((df["utilization_ratio"] < 0) | (df["utilization_ratio"] > 1)).sum()
    )
}

audit_summary

{'rows': 100000,
 'columns': 40,
 'missing_values': 0,
 'duplicate_rows': 0,
 'duplicate_customer_ids': 0,
 'churn_rate': np.float64(19.46),
 'invalid_credit_scores': 0,
 'invalid_utilization': 0}